Traceback (most recent call last):
  File "/Users/kashnitskiyy/opt/anaconda3/envs/mlcourse/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/kashnitskiyy/opt/anaconda3/envs/mlcourse/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kashnitskiyy/opt/anaconda3/envs/mlcourse/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kashnitskiyy/opt/anaconda3/envs/mlcourse/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kashnitskiyy/opt/anaconda3/envs/mlcourse/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/kashnitskiyy/opt/anaconda3/envs/mlcourse/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/kashnitskiyy/opt/anaconda3/envs/mlcourse/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/kashnitskiyy/opt/anaconda3/envs/mlcourse/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import eli5

eli5.show_weights(
    estimator=tfidf_logit_pipeline.named_steps["logit"],
    vec=tfidf_logit_pipeline.named_steps["tf_idf"],
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/var/folders/xs/x4nxtnxd4qq06sg5z0x951q1q7mkqq/T/ipykernel_53539/2603279008.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0meli5[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m eli5.show_weights(
[1;32m      4[0m     [0mestimator[0m[0;34m=[0m[0mtfidf_logit_pipeline[0m[0;34m.[0m[0mnamed_steps[0m[0;34m[[0m[0;34m"logit"[0m[0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0mvec[0m[0;34m=[0m[0mtfidf_logit_pipeline[0m[0;34m.[0m[0mnamed_steps[0m[0;34m[[0m[0;34m"tf_idf"[0m[0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'eli5'
ModuleNotFoundError: No module named 'eli5'

